### ISSUE TITLE
Create Upload Page

### ISSUE THREAD

**Issue by divlogic** [codefordenver/ideaLab#122]
Sub issues:
#147
- [x] Submit these values with the file: name, email, comments
- [x] Display errors for fields

Add ux features to upload page #149
- [x] Add success or fail state for upload
- [x] On navigate away warning that download will be cancelled

Validate uploads #148
- [x] Handle File size of 100 mb uploads
- [x] Validate filetype as .stl only
- [x] Present only .stl as an option, copy to inform

- [x] Include auth as part of mvp

Related:
#123
- [x] Submit file from front end to dropbox directly
- [x] Implement design on upload page #215
